import type { MetadataRoute } from "next";
import { clientProfiles, serviceProfiles } from "@/content/profiles";
import { insights } from "@/content/insights";
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    "",
    "/about",
    "/about/team",
    "/services",
    ...serviceProfiles.map((s) => `/services/${s.slug}`),
    "/clients",
    ...clientProfiles.map((c) => `/clients/${c.slug}`),
    "/about/pressroom",
    "/careers",
    "/governance",
    "/governance/risk-management",
    "/investor-relations",
    "/platforms",
    "/why-equities",
    "/help",
    "/open-account",
    "/market-news",
    "/market-announcements",
    "/news",
    "/insights/market-notes",
    "/insights/guides",
    "/insights/library",
    ...insights.map((i) => `/insights/${i.slug}`),
    "/tools",
    "/tools/calculators",
    "/tools/stock-screener",
    "/tools/watchlist",
    "/tools/portfolio",
    "/insights",
    "/resources",
    "/get-started",
    "/get-started/individual",
    "/get-started/corporate",
    "/contact",
    "/privacy",
    "/disclosures",
    "/accessibility",
  ].map((path) => ({ url: `https://caballes-go.com${path}` }));
}
